repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe]

  - repo: https://github.com/LilSpazJoekp/docstrfmt
    hooks:
      - id: docstrfmt
        require_serial: true
    rev: v1.5.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    hooks:
      - id: flake8
    rev: 4.0.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        args: []
        exclude: "tests"
        additional_dependencies:
          - types-requests==2.27.20
