repos:
  - repo: https://github.com/LilSpazJoekp/docstrfmt
    rev: v1.5.1
    hooks:
      - id: docstrfmt
        language_version: python3
        exclude: "docs"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3
