name: code coverage
on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
        pip install .
    - name: Build coverage file
      run: |
        pytest --cache-clear --cov > pytest-coverage.txt
      env:
        NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
        USER_NAME: ${{ secrets.USER_NAME }}
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
