name: pytest
on:
  - push
  - pull_request
jobs:
  pytest:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Environment ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install .
      - name: Test with pytest
        run: |
          pytest
        env:
          NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
          USER_NAME: ${{ secrets.USER_NAME }}
